// src/types/models.ts
import type { DBSchema } from 'idb';

/**
 * Represents the metadata for a file associated with a specific case.
 */
export interface CaseFileMetadata {
  id: string; // Unique identifier for the file or folder metadata (e.g., UUID)
  caseId: string; // Identifier for the case this item belongs to
  parentId: string | null; // ID of the parent folder, or null for root level items
  type: 'file' | 'folder' | string; // Renamed from itemType back to type, and allow general string for mime types
  name: string; // Name of the file or folder (renamed from fileName for consistency)
  fileType?: string; // e.g., 'application/pdf', 'image/jpeg' (only relevant for files)
  size?: number; // Added: fileSize was used as 'size'
  createdAt: Date; // Changed from string to Date
  updatedAt: Date; // Changed from string to Date
  path: string; // Added: path is used for navigation and breadcrumbs
  content?: Blob | null; // File content, stored by localDbService
  isDeleted?: boolean; // Added: isDeleted is used for soft deletes
  lastModified?: number; // Added: lastModified from File object
  description?: string;
  tags?: string[];
  accessControl?: 'private' | 'shared'; // Or more granular
}

// /**
//  * Represents a contact (Client, Attorney, Witness, etc.).
//  */
// export interface Contact {
//   id: string; // Unique identifier (e.g., UUID)
//   name: string;
//   email: string;
//   phone?: string; // Optional phone number
//   company?: string; // Optional company name
//   type: string; // e.g., 'Client', 'Attorney'
//   caseFileNumbers?: string[]; // Associated case file numbers
//   createdAt?: Date; // Optional: Track creation time
//   updatedAt?: Date; // Optional: Track update time
// }

/**
 * Represents a legal Case or case.
 */
export interface Case {
  id: string; // Unique identifier (e.g., UUID or Case File Number if unique)
  caseFileNumber: string; // The primary case identifier shown to users
  title: string; // e.g., "Smith v. Jones Mediation"
  status: string; // e.g., 'Open', 'Closed', 'Pending'
  parties?: string[]; // List of involved parties (could reference Contact IDs)
  description?: string;
  createdAt?: Date;
  updatedAt?: Date; // Make this optional as it's not always present initially
  type?: string; // Added: e.g., 'Divorce', 'Civil', 'Family'
  clientName?: string; // Added: Primary client's name
  email?: string; // Added: Primary client's email
  phone?: string; // Added: Primary client's phone
  address?: string; // Added: Primary client's address
  intakeForm?: any; // Added: To store intake form data, consider a specific type later
  caseFileName?: string; // Added: Optional file name for the case if different from title
  lastUpdated?: string; // Added from ClientDetailsPage logic, make optional
}

/**
 * Represents a task associated with the mediation process.
 */
export interface Task {
    id: string; // Unique identifier
    title: string;
    description?: string;
    status: 'Todo' | 'In Progress' | 'Done' | 'Blocked';
    priority?: 'Low' | 'Medium' | 'High';
    dueDate?: Date; // Property type is Date
    assignedTo?: string; // Could reference a Contact ID or user ID
    caseId?: string; // Link task to a specific case
    caseFileNumber?: string; // Optional: Associated case file number
    caseTitle?: string; // Optional: Associated case title
    createdAt: Date; // Property type is Date
    updatedAt: Date;
}

/**
 * Represents a document stored in the system.
 */
export interface Document {
    id: string; // Unique identifier
    title: string;
    type: string; // e.g., 'Agreement', 'Notes', 'Template'
    content?: string | object; // Could be text content or structured data
    caseId?: string; // Link document to a specific case
    createdAt: Date;
    updatedAt: Date;
    storageRef?: string; // If content is stored elsewhere (like CaseFileMetadata)
}

/**
 * Represents a note, often linked to a specific case or session.
 */
export interface Note {
    id: string; // Unique identifier
    caseFileNumber: string; // Link note to a specific case using its file number
    title?: string;
    content: string; // The actual note text (or potentially structured data)
    tags?: string[];
    createdAt: Date; // Property type is Date
    updatedAt: Date;
}

/**
 * Represents an event in the timeline of a case.
 */
export interface TimelineEvent {
  id?: string; // Optional: will be auto-generated by IndexedDB if not provided
  caseId: string;
  title: string;
  type: string; // e.g., 'hearing', 'filing', 'client-meeting', 'deadline'
  description: string;
  date: string; // ISO string format for date
  createdAt?: string; // ISO string format
  updatedAt?: string; // ISO string format
}

export interface Meeting {
  id: string; // UUID
  caseId: string;
  title: string;
  date: string; // ISO string format for date and time
  location?: string; // Optional: can be physical or virtual (e.g., "Zoom Link")
  participants?: string[]; // Array of participant names or IDs
  agenda?: string; // Markdown or plain text
  notes?: string; // Markdown or plain text, for minutes or action items
  createdAt: string; // ISO string format
  updatedAt: string; // ISO string format
}

// Define a basic Client interface if it's used elsewhere or planned for future use
export interface Client {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  // Add other client-specific fields here
}

// Interface for the structure of a saved form
export interface SavedForm {
  id: string; // Unique identifier for the form
  formTitle: string;
  formDescription?: string;
  statementDate?: string;
  sections: any[];
}

/**
 * Represents an item in a case checklist.
 */
export interface ChecklistItem {
  id: string;          // Unique ID for the checklist item
  caseId: string;      // ID of the case this item belongs to
  text: string;        // The description of the checklist item
  completed: boolean;  // Property type is boolean
  category?: string;   // Optional category for the item (e.g., "intake", "agreement")
  createdAt: string;   // ISO string timestamp
  updatedAt: string;   // ISO string timestamp
}

// --- IndexedDB Schema Definition ---
// The values in the 'indexes' object should be the keyPath for the index (string or string[]).
// These should match the property names in the corresponding interfaces.
export interface MediatorMateDBSchema extends DBSchema {
  cases: {
    key: string;
    value: Case;
    indexes: { 'caseFileNumber': 'caseFileNumber'; 'clientName': 'clientName'; 'status': 'status'; 'title': 'title'; };
  };
  notes: {
    key: string;
    value: Note;
    indexes: { 'by-caseFileNumber': 'caseFileNumber'; 'createdAt': 'createdAt'; }; // 'createdAt' is a property of Note
  };
  // contacts: { // Commenting out as Contact interface is commented out
  //   key: string;
  //   value: Contact; // Contact interface is commented out above
  //   indexes: { 'by-name': 'name'; 'email': 'email'; 'type': 'type'; };
  // };
  documents: {
    key: string;
    value: Document;
    indexes: { 'by-caseId': 'caseId'; 'by-type': 'type'; 'title': 'title'; };
  };
  tasks: {
    key: string;
    value: Task;
    indexes: { 'by-status': 'status'; 'by-dueDate': 'dueDate'; 'caseId': 'caseId'; 'priority': 'priority'; }; // 'dueDate' is a property of Task
  };
  caseFiles: {
    key: string;
    value: CaseFileMetadata;
    indexes: { 'by-caseId': 'caseId'; 'by-name': 'name'; 'by-parent': ['caseId', 'parentId']; 'type': 'type'; };
  };
  timeline: {
    key: string;
    value: TimelineEvent;
    indexes: { 'caseId': 'caseId'; 'date': 'date'; 'type': 'type'; };
  };
  checklistItems: {
    key: string;
    value: ChecklistItem;
    indexes: { 'caseId': 'caseId'; 'completed': 'completed'; 'category': 'category'; 'createdAt': 'createdAt'; }; // 'completed' is a property of ChecklistItem
  };
  meetings: {
    key: string;
    value: Meeting;
    indexes: { 'caseId': 'caseId'; 'date': 'date'; 'title': 'title'; };
  };
  forms: {
    key: string;
    value: SavedForm;
    indexes: { 'by-formTitle': 'formTitle'; };
  };
}